### ISSUE TITLE
Gestion quand Failed

### ISSUE THREAD

**Issue by AudreyCLEVY** [etalab-ia/eg1#32]

**Comment by dtrckd** [comment]
On peut désormais "retry" un experimentset pour repasser sur tout les run fail (par exemple albert-api qui a un taux d'erreur assez élevé lorsque surchargé, voir #48 .

Par contre, on ne peut pas savoir, lorsque qu'un expé échoue, si cela signifie que toutes les expé du set vont échoué aussi. il y a aucune manière de savoir ca à lavance, les epxé set sont trop versatile. Si l'utilisateur a lancé un expé avec des paramètres erronés, c'est a lui de stopper son expe. Et c'est donc ce ticket qui traite la question #31

**Comment by AudreyCLEVY** [comment]
est-ce qu'on pourrait mettre un "filtre" pour que si la réponse du llm est vide, alors on ne fait pas  tourner la partie "EVAL"?

**Comment by dtrckd** [comment]
Je pense que c'est déja le cas (tasks.py), non ?

![Image](https://github.com/user-attachments/assets/27a47d8b-5e77-483a-a1e8-469778cc026a)
