### ISSUE TITLE
[UI] Add a status bar to the experimentset cards view

### ISSUE THREAD

**Issue by dtrckd** [etalab-ia/eg1#47]
It will be useful to have on the expermentset a view of the statuses of each experiment cards, for example : 

- is an expeset currently running/failing ?
- the percent success (finished without failure) ?
- the percent failed (finished with failure) ?

⚠ Pain point :  an ouput/answer generation can be success, while some associated metrics/observation can be failed.

**Comment by dtrckd** [comment]
This relates to #38 but is different because 38 concerns the state of ALL experiments, while this thix ticket is at the experiment_set level.

**Comment by AudreyCLEVY** [comment]
<img width="1109" alt="Image" src="https://github.com/user-attachments/assets/b8a42042-601e-4c1f-81e1-4570312a82c7" />
the idea is to have at least one status item in each ExpSET in addition to the current ones (readme, id, nb_exp, creation date, etc.).

**Comment by dtrckd** [comment]
The current implementation just misses the percentage of finished experiment in a set which can be a cool indicator, but I think it's not a priority so I close. Don't hesitate to have a look if I you wan to implement it.
