### ISSUE TITLE
[UI] Refresh

### ISSUE THREAD

**Issue by dtrckd** [etalab-ia/eg1#50]
Something I always do, is moving accros menu to "refresh" the state an experimentset (number of num_try, sucess etc.), and as we cannot refresh the page with "Ctrl-R", because it goes back to the epxset main view. So it is  tedious as we need to do 3 actions/click  in order  to go to the expset/expe we are visualizing.

A solution for this issu might be:
- [x] (easy) to add a refresh button that will reload the dataframes/data
- [ ] (harder) add specific url to each view/tab in order to be able to refresh with "Ctrl-R"

**Comment by AudreyCLEVY** [comment]
@dtrckd : https://github.com/etalab-ia/eg1/pull/53

**Comment by AudreyCLEVY** [comment]
I use "easy" solution at first
